
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.TextView outputTextView;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Table numPad;
	
	private global::Gtk.Button buttonNum;
	
	private global::Gtk.Button buttonNum1;
	
	private global::Gtk.Button buttonNum2;
	
	private global::Gtk.Button buttonNum3;
	
	private global::Gtk.Button buttonNum4;
	
	private global::Gtk.Button buttonNum5;
	
	private global::Gtk.Button buttonNum6;
	
	private global::Gtk.Button buttonNum7;
	
	private global::Gtk.Button buttonNum8;
	
	private global::Gtk.Button buttonNum9;
	
	private global::Gtk.Button buttonNumDec;
	
	private global::Gtk.Button buttonNumToggle;
	
	private global::Gtk.Table opPad;
	
	private global::Gtk.Button buttonAdd;
	
	private global::Gtk.Button buttonClear;
	
	private global::Gtk.Button buttonDiv;
	
	private global::Gtk.Button buttonMod;
	
	private global::Gtk.Button buttonMult;
	
	private global::Gtk.Button buttonPop;
	
	private global::Gtk.Button buttonPush;
	
	private global::Gtk.Button buttonSub;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.outputTextView = new global::Gtk.TextView ();
		this.outputTextView.CanFocus = true;
		this.outputTextView.Name = "outputTextView";
		this.outputTextView.Editable = false;
		this.outputTextView.CursorVisible = false;
		this.outputTextView.AcceptsTab = false;
		this.vbox1.Add (this.outputTextView);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.outputTextView]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.numPad = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
		this.numPad.Name = "numPad";
		this.numPad.RowSpacing = ((uint)(6));
		this.numPad.ColumnSpacing = ((uint)(6));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum = new global::Gtk.Button ();
		this.buttonNum.CanFocus = true;
		this.buttonNum.Name = "buttonNum";
		this.buttonNum.UseUnderline = true;
		this.buttonNum.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.numPad.Add (this.buttonNum);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum1 = new global::Gtk.Button ();
		this.buttonNum1.CanFocus = true;
		this.buttonNum1.Name = "buttonNum1";
		this.buttonNum1.UseUnderline = true;
		this.buttonNum1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.numPad.Add (this.buttonNum1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum1]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum2 = new global::Gtk.Button ();
		this.buttonNum2.CanFocus = true;
		this.buttonNum2.Name = "buttonNum2";
		this.buttonNum2.UseUnderline = true;
		this.buttonNum2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.numPad.Add (this.buttonNum2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum2]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum3 = new global::Gtk.Button ();
		this.buttonNum3.CanFocus = true;
		this.buttonNum3.Name = "buttonNum3";
		this.buttonNum3.UseUnderline = true;
		this.buttonNum3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.numPad.Add (this.buttonNum3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum3]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum4 = new global::Gtk.Button ();
		this.buttonNum4.CanFocus = true;
		this.buttonNum4.Name = "buttonNum4";
		this.buttonNum4.UseUnderline = true;
		this.buttonNum4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.numPad.Add (this.buttonNum4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum4]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum5 = new global::Gtk.Button ();
		this.buttonNum5.CanFocus = true;
		this.buttonNum5.Name = "buttonNum5";
		this.buttonNum5.UseUnderline = true;
		this.buttonNum5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.numPad.Add (this.buttonNum5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum6 = new global::Gtk.Button ();
		this.buttonNum6.CanFocus = true;
		this.buttonNum6.Name = "buttonNum6";
		this.buttonNum6.UseUnderline = true;
		this.buttonNum6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.numPad.Add (this.buttonNum6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum6]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum7 = new global::Gtk.Button ();
		this.buttonNum7.CanFocus = true;
		this.buttonNum7.Name = "buttonNum7";
		this.buttonNum7.UseUnderline = true;
		this.buttonNum7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.numPad.Add (this.buttonNum7);
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum8 = new global::Gtk.Button ();
		this.buttonNum8.CanFocus = true;
		this.buttonNum8.Name = "buttonNum8";
		this.buttonNum8.UseUnderline = true;
		this.buttonNum8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.numPad.Add (this.buttonNum8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum8]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNum9 = new global::Gtk.Button ();
		this.buttonNum9.CanFocus = true;
		this.buttonNum9.Name = "buttonNum9";
		this.buttonNum9.UseUnderline = true;
		this.buttonNum9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.numPad.Add (this.buttonNum9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNum9]));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNumDec = new global::Gtk.Button ();
		this.buttonNumDec.CanFocus = true;
		this.buttonNumDec.Name = "buttonNumDec";
		this.buttonNumDec.UseUnderline = true;
		this.buttonNumDec.Label = global::Mono.Unix.Catalog.GetString (".");
		this.numPad.Add (this.buttonNumDec);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNumDec]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		// Container child numPad.Gtk.Table+TableChild
		this.buttonNumToggle = new global::Gtk.Button ();
		this.buttonNumToggle.CanFocus = true;
		this.buttonNumToggle.Name = "buttonNumToggle";
		this.buttonNumToggle.UseUnderline = true;
		this.buttonNumToggle.Label = global::Mono.Unix.Catalog.GetString ("+/-");
		this.numPad.Add (this.buttonNumToggle);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.numPad [this.buttonNumToggle]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		this.hbox3.Add (this.numPad);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.numPad]));
		w14.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.opPad = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.opPad.Name = "opPad";
		this.opPad.RowSpacing = ((uint)(6));
		this.opPad.ColumnSpacing = ((uint)(6));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.opPad.Add (this.buttonAdd);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonAdd]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("C");
		this.opPad.Add (this.buttonClear);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonClear]));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonDiv = new global::Gtk.Button ();
		this.buttonDiv.CanFocus = true;
		this.buttonDiv.Name = "buttonDiv";
		this.buttonDiv.UseUnderline = true;
		this.buttonDiv.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.opPad.Add (this.buttonDiv);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonDiv]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonMod = new global::Gtk.Button ();
		this.buttonMod.CanFocus = true;
		this.buttonMod.Name = "buttonMod";
		this.buttonMod.UseUnderline = true;
		this.buttonMod.Label = global::Mono.Unix.Catalog.GetString ("%");
		this.opPad.Add (this.buttonMod);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonMod]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonMult = new global::Gtk.Button ();
		this.buttonMult.CanFocus = true;
		this.buttonMult.Name = "buttonMult";
		this.buttonMult.UseUnderline = true;
		this.buttonMult.Label = global::Mono.Unix.Catalog.GetString ("X");
		this.opPad.Add (this.buttonMult);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonMult]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonPop = new global::Gtk.Button ();
		this.buttonPop.CanFocus = true;
		this.buttonPop.Name = "buttonPop";
		this.buttonPop.UseUnderline = true;
		this.buttonPop.Label = global::Mono.Unix.Catalog.GetString (")");
		this.opPad.Add (this.buttonPop);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonPop]));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		// Container child opPad.Gtk.Table+TableChild
		this.buttonPush = new global::Gtk.Button ();
		this.buttonPush.CanFocus = true;
		this.buttonPush.Name = "buttonPush";
		this.buttonPush.UseUnderline = true;
		this.buttonPush.Label = global::Mono.Unix.Catalog.GetString ("(");
		this.opPad.Add (this.buttonPush);
		// Container child opPad.Gtk.Table+TableChild
		this.buttonSub = new global::Gtk.Button ();
		this.buttonSub.CanFocus = true;
		this.buttonSub.Name = "buttonSub";
		this.buttonSub.UseUnderline = true;
		this.buttonSub.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.opPad.Add (this.buttonSub);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.opPad [this.buttonSub]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		this.hbox3.Add (this.opPad);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.opPad]));
		w23.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w24.Position = 1;
		w24.Expand = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 580;
		this.DefaultHeight = 471;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonNumToggle.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNumDec.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum9.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum8.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum7.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum6.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum5.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum4.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum3.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum2.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum1.Clicked += new global::System.EventHandler (this.numClicked);
		this.buttonNum.Clicked += new global::System.EventHandler (this.numClicked);
	}
}
